// Code Generated by Sidekick is for learning and experimentation purposes only.
/**
 * Function to extract filters from a string and convert them into key-value pairs.
 * @param {string} filterString - The input string containing filters.
 * @returns {object} - An object containing key-value pairs of filters.
 */
function getFilters(filterString) {
    // Remove the prefix 'filters = [' and the suffix ']'

    debugger;
    const filterContent = filterString.replace('filters = [', '').replace(']', '').trim();
    
    // Split the filter content by ', ' to get individual filters
    const filterArray = filterContent.split(', ');

    // Create an object to hold the key-value pairs
    const filters = {};

     debugger;
    // Iterate over the filter array and split each filter into key and value
    filterArray.forEach(filter => {
        const [key, value] = filter.split(' = ').map(item => item.trim());
        filters[key] = value;
    });

    console.log(filters);
    return JSON.stringify(filters);
}
 
